import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import colors from "colors";

import { ThemeProvider } from "@/components/theme-provider";
import Sidebar from "@/components/Sidebar";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={
            (inter.className,
            "w-full max-w-[1440px] h-screen flex mx-auto max-md:overflow-hidden")
          }
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <aside className="w-[25%] border-r-2 max-lg:w-[15%]">
              <Sidebar />
            </aside>
            <main className="w-[75%] max-lg:w-[85%] px-4 overflow-scroll">
              {children}
            </main>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
